Repository orange-cloudavenue/terraform-cloudavenue-nats, pull requests merged in 2023-11, with the labels that each got.

#2 feat: add feature nat module
  .gitignore
  .terraform-docs.yml
  .tflint.hcl
  CONTRIBUTING.md
  Makefile
  README.md
  main.tf
  tests/nat.tftest.hcl
  tests/setup/main.tf
  variables.tf
  versions.tf
Labels: Feature, size/M

#6 feat: add dependabot yaml file
  .github/dependabot.yml
  .github/workflows/dependabot_changelog.yml
Labels: Feature, size/S

#9 fix: pylint issues
  main.tf
  outputs.tf
  variables.tf
Labels: size/XS, Fix

#11 feat: activate workflow
  .github/workflows/dependabot_changelog.yml
  .github/workflows/lint.yml
Labels: Feature, size/XS

#13 fix: improve readme
  README.md
Labels: size/XS, Fix

#16 chore: add CODEOWNERS
  .github/CODEOWNERS
Labels: size/XS, Chore

#18 feat: add changelog
  .changelog/.gitkeep
  .github/workflows/generate_changelog.yml
  .github/workflows/release.yml
  CHANGELOG.md
  README.md
Labels: Feature, size/M
